services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: randomNumberService
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} ${POSTGRES_DB}"]    
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "
      npx prisma migrate dev &&
      make start_randomNumberService
      "
    depends_on:
      -  postgres
    restart: always

  nginx:
    image: ilyashikman/nginx:latest
    container_name: nginx
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./volumes/build/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main
      
volumes:
  pgdata:
